In [1]:
import numpy as np
import cv2

img = cv2.imread("opencvLogo.png")
cv2.namedWindow("Image",cv2.WINDOW_NORMAL)
cv2.imshow("Image",img)

cv2.waitKey(0)

cv2.imwrite("output.jpg", img)

True

In [2]:
img = cv2.imread("opencvLogo.png",1)
img

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

In [3]:
type(img)

numpy.ndarray

In [4]:
len(img)

521

In [5]:
len(img[0])

1600

In [6]:
len(img[0][0])

3

In [7]:
img.shape

(521, 1600, 3)

In [8]:
img.dtype

dtype('uint8')

In [9]:
2**8

256

In [10]:
img[10, 5]

array([255, 255, 255], dtype=uint8)

In [11]:
img[:,:,0]

array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], dtype=uint8)

In [12]:
img.size

2500800

# Black Screen

In [13]:
black = np.zeros([150,200,1],'uint8')
cv2.imshow('Black',black)
print(black[0,0,:])
cv2.waitKey(0)
cv2.destroyAllWindows()

[0]


In [14]:
ones = np.ones([150,200,3],'uint8')
cv2.imshow('Ones',ones)
print(ones[0,0,:])
cv2.waitKey(0)
cv2.destroyAllWindows()

[1 1 1]


# White Screen

In [15]:
white = np.ones([150,200,3],'uint16')
white *= (2**16-1)
cv2.imshow("White", white)
print(white[0,0,:])
cv2.waitKey(0)
cv2.destroyAllWindows()

[65535 65535 65535]


# Blue Screen

In [16]:
color = ones.copy()
color[:,:] = (255,0,0)
cv2.imshow("Blue", color)
print(color[0,0,:])
cv2.waitKey(0)
cv2.destroyAllWindows()

[255   0   0]


# Butterfly


In [19]:
color = cv2.imread('butterfly.jpg',1)
cv2.imshow("Image",color)
cv2.moveWindow("Image",0,0)
print(color.shape)
height, width, channels = color.shape

b,g,r = cv2.split(color)

rgb_split = np.empty([height,width*3,3],'uint8')

rgb_split[:, 0:width] = cv2.merge([b,b,b])
rgb_split[:, width:width*2] = cv2.merge([g,g,g])
rgb_split[:, width*2:width*3] = cv2.merge([r,r,r])

cv2.imshow("Channels",rgb_split)
cv2.moveWindow("Channels",0,height)

hsv = cv2.cvtColor(color, cv2.COLOR_BGR2HSV)
h,s,v = cv2.split(hsv)
hsv_split = np.concatenate((h,s,v), axis=1)
cv2.imshow("Split HSV", hsv_split)

cv2.waitKey(0)
cv2.destroyAllWindows()

(356, 493, 3)


# Pixel manuplation and filtering

In [20]:
color = cv2.imread('butterfly.jpg',1)

gray = cv2.cvtColor(color, cv2.COLOR_RGB2GRAY)
cv2.imwrite("gray.jpg", gray)

b = color[:,:,0]
g = color[:,:,1]
r = color[:,:,2]

rgba = cv2.merge((b,g,r,g))
cv2.imwrite("rgba.png", rgba)


True

# Blur, dilation and erosion

In [3]:
image = cv2.imread("thresh.jpg")
cv2.imshow("Original", image)

blur = cv2.GaussianBlur(image, (5,55),0)
cv2.imshow("Blur", blur)

kernel = np.ones((5,5),'uint8')

dilate = cv2.dilate(image,kernel,iterations=1)
erode = cv2.erode(image,kernel,iterations=1)

cv2.imshow("Dilate", dilate)
cv2.imshow("Erode", erode)

cv2.waitKey(0)
cv2.destroyAllWindows()

# Scale and Rotate Image

In [5]:
img = cv2.imread("players.jpg")

#Scale
img_half = cv2.resize(img, (0,0), fx=0.5, fy=0.5)
img_streach = cv2.resize(img, (600,600))
img_streach_near = cv2.resize(img, (600,600), interpolation=cv2.INTER_NEAREST)

cv2.imshow("Half", img_half)
cv2.imshow("Streach", img_streach)
cv2.imshow("Streach Near", img_streach_near)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [6]:
# Rotation
M = cv2.getRotationMatrix2D((0,0), -30, 1)
rotated = cv2.warpAffine(img, M, (img.shape[1], img.shape[0]))
cv2.imshow("Rotated", rotated)

cv2.waitKey(0)
cv2.destroyAllWindows()

# Use video input

In [7]:
cap = cv2.VideoCapture(0)

while(True):
    ret, frame = cap.read()

    frame = cv2.resize(frame, (0,0), fx=0.5, fy=0.5)
    cv2.imshow("Frame", frame)

    ch = cv2.waitKey(1)
    if ch & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

# Create custom interface

In [11]:
cap = cv2.VideoCapture(0)

color = (0,255,0)
line_width = 3
radius = 100
point = (0,0)

def click(event, x, y, flags, param):
    global point, pressed
    if event == cv2.EVENT_LBUTTONDOWN:
        print("Pressed", x, y)
        point = (x, y)

cv2.namedWindow("Frame")
cv2.setMouseCallback("Frame", click)

while(True):
    ret, frame = cap.read()

    frame = cv2.resize(frame, (0,0), fx=1, fy=1)
    cv2.circle(frame, point, radius, color, line_width)
    cv2.imshow("Frame", frame)

    ch = cv2.waitKey(1)
    if ch & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

Pressed 226 164
Pressed 377 270
Pressed 377 330
Pressed 363 375
Pressed 262 356


# Create Simple Drawing App

In [33]:
import numpy as np
import cv2

# Global variables
canvas = np.ones([500,500,3],'uint8')*255

color = (0,255,0)
radius = 5
pressed = False

# click callback
def click(event, x, y, flags, param):
    global canvas, pressed
    if event == cv2.EVENT_LBUTTONDOWN:
        pressed = True
        cv2.circle(canvas, (x,y), radius, color,-1)
    elif event == cv2.EVENT_MOUSEMOVE and pressed == True:
        cv2.circle(canvas, (x,y), radius, color,-1)
    elif event == cv2.EVENT_LBUTTONUP:
        pressed = False

# window initialization and callback assignment
cv2.namedWindow("canvas")
cv2.setMouseCallback("canvas", click)

# Forever draw loop
while True:

    cv2.imshow("canvas",canvas)
	# key capture every 1ms
    ch = cv2.waitKey(1)
    if ch & 0xFF == ord('q'):
        break
    elif ch & 0xFF == ord('b'):
        color = (255,0,0)
    elif ch & 0xFF == ord('g'):
        color = (0,255,0)
	
cv2.destroyAllWindows()

# Simple thesholding

In [2]:
import numpy as np
import cv2

bw = cv2.imread("detect_blob.png", 0)
height, width = bw.shape[0:2]
cv2.imshow("Original BW",bw)

binary = np.zeros([height, width, 1], 'uint8')

thresh = 85

for row in range(0,height):
    for col in range(0, width):
        if bw[row][col] > thresh:
            binary[row][col] = 255

cv2.imshow("Slow Binary", binary)

ret, thresh = cv2.threshold(bw, thresh, 255, cv2.THRESH_BINARY)
cv2.imshow("CV Threshold", thresh)

cv2.waitKey(0)
cv2.destroyAllWindows()

# Adaptive Thresholding

In [4]:
import numpy as np
import cv2

img = cv2.imread('sudoku.png', 0)
cv2.imshow("Original", img)

ret, thresh_basic = cv2.threshold(img, 70, 255, cv2.THRESH_BINARY)
cv2.imshow("Basic Binary", thresh_basic)

thresh_adapt = cv2.adaptiveThreshold(img, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY, 115, 1)
cv2.imshow("Adaptive Threshold", thresh_adapt)

cv2.waitKey(0)
cv2.destroyAllWindows()

# Skin detection

In [18]:
import numpy as np
import cv2

img = cv2.imread("faces.jpeg", 1)
img = cv2.resize(img, (0,0), fx=0.14, fy=0.14)
hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
h = hsv[:,:,0]
s = hsv[:,:,1]
v = hsv[:,:,2]

hsv_split = np.concatenate((h,s,v), axis=1)
cv2.imshow("Split HSV", hsv_split)

ret, min_sat = cv2.threshold(s, 40, 255, cv2.THRESH_BINARY)
cv2.imshow("Sat Filter", min_sat)

ret, max_hue = cv2.threshold(h, 15, 255, cv2.THRESH_BINARY_INV)
cv2.imshow("Hue Filter", max_hue)

final = cv2.bitwise_and(min_sat, max_hue)
cv2.imshow("Final", final)

cv2.imshow("Original", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Contour object Detection

In [1]:
import numpy as np
import cv2

img = cv2.imread("detect_blob.png", 1)
gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
thresh = cv2.adaptiveThreshold(gray, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY, 155, 1)
cv2.imshow("Binary", thresh)

contours, hierarchy = cv2.findContours(thresh, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)

img2 = img.copy()
index = -1
thickness = 4
color = (255,0,255)

cv2.drawContours(img2, contours, index, color, thickness)
cv2.imshow("Contours", img2)

cv2.waitKey(0)
cv2.destroyAllWindows()

# Area, Perimerter, center, and curvature

In [1]:
import numpy as np
import cv2

img = cv2.imread("detect_blob.png", 1)
gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
thresh = cv2.adaptiveThreshold(gray, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY, 155, 1)
cv2.imshow("Binary", thresh)

contours, hierarchy = cv2.findContours(thresh, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)

img2 = img.copy()
index = -1
thickness = 4
color = (255,0,255)

objects = np.zeros([img.shape[0], img.shape[1], 3], 'uint8')
for c in contours:
    cv2.drawContours(objects, [c], -1, color, -1)

    area = cv2.contourArea(c)
    perimeter = cv2.arcLength(c, True)
    
    M = cv2.moments(c)
    
    try:
        cx = int(M['m10']/M['m00'])
        cy = int(M['m01']/M['m00'])
        cv2.circle(objects, (cx, cy), 4, (0,0,255), -1)
    except:
        pass
    print("Area: {}, Perimeter: {}".format(area, perimeter))

cv2.imshow("Contours", objects)

cv2.waitKey(0)
cv2.destroyAllWindows()

Area: 13097.0, Perimeter: 752.6274166107178
Area: 0.0, Perimeter: 0.0
Area: 10067.0, Perimeter: 400.8284270763397
Area: 7785.0, Perimeter: 329.22034418582916
Area: 4160.0, Perimeter: 258.0
Area: 1672.0, Perimeter: 160.48528122901917
Area: 14530.5, Perimeter: 1226.3544620275497
Area: 5617.5, Perimeter: 450.0660150051117
Area: 7758.0, Perimeter: 485.65685415267944
Area: 1017.5, Perimeter: 137.49747359752655
Area: 5026.0, Perimeter: 444.3675308227539
Area: 8836.0, Perimeter: 449.7644990682602
Area: 551.5, Perimeter: 93.41421353816986
Area: 2706.5, Perimeter: 194.7523068189621
Area: 1647.5, Perimeter: 152.12489080429077
Area: 764.0, Perimeter: 105.74011421203613
Area: 3497.5, Perimeter: 251.0710676908493
Area: 8558.5, Perimeter: 346.2914116382599
Area: 8871.0, Perimeter: 378.8284270763397
Area: 750.0, Perimeter: 102.9116872549057
Area: 1642.0, Perimeter: 152.36753058433533
Area: 1.0, Perimeter: 4114.82842707634


# Canny edge detection

In [1]:
import numpy as np
import cv2

img = cv2.imread("tomatoes.jpg", 1)

hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
res, thresh = cv2.threshold(hsv[:,:,0], 25, 255, cv2.THRESH_BINARY_INV)
cv2.imshow("Thresh", thresh)

edges = cv2.Canny(img, 100, 70)
cv2.imshow("Canny", edges)

cv2.waitKey(0)
cv2.destroyAllWindows() 

# Assign object ID and attributes

In [11]:
import numpy as np
import cv2
import random

img = cv2.imread("fuzzy.png",1)
cv2.imshow("Original", img)

gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
blur = cv2.GaussianBlur(gray, (3,3), 0)

thresh = cv2.adaptiveThreshold(blur, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY_INV, 155, 1)
cv2.imshow("Binary", thresh)

contours, hierarchy = cv2.findContours(thresh, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)

print(len(contours))

filtered = []
for c in contours:
    if cv2.contourArea(c) < 3000:
        continue
    filtered.append(c)

print(len(filtered))

objects = np.zeros([img.shape[0], img.shape[1], 3], 'uint8')
for c in filtered:
    col = (random.randint(0,255), random.randint(0,255), random.randint(0,255))
    cv2.drawContours(objects,[c], -1, col, -1)
    area = cv2.contourArea(c)
    p = cv2.arcLength(c,True)
    print(area,p)

cv2.imshow("Contours", objects)

cv2.waitKey(0)
cv2.destroyAllWindows()

1952
3
4915.0 304.85281229019165
29855.0 810.6416970491409
17276.0 563.1370830535889


# Application of template matching

In [14]:
import numpy as np
import cv2

template = cv2.imread('template.jpg',0)
frame = cv2.imread("players.jpg",0)

cv2.imshow("Frame", frame)
cv2.imshow("Template", template)

result = cv2.matchTemplate(frame, template, cv2.TM_CCOEFF_NORMED)

min_val, max_val, min_loc, max_loc = cv2.minMaxLoc(result)
cv2.circle(result, max_loc, 15,255, 2)
cv2.imshow("Matching", result)

cv2.waitKey(0)
cv2.destroyAllWindows()

# Face Detection

In [25]:
import numpy as np
import cv2

img = cv2.imread("faces.jpeg", 1)
img = cv2.resize(img, (0,0), fx=.2, fy=.2)
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
path = "haarcascade_frontalface_default.xml"

face_cascade = cv2.CascadeClassifier(path)

faces = face_cascade.detectMultiScale(gray, scaleFactor=1.05, minNeighbors=5, minSize=(40,40))
print(len(faces))

for (x, y, w, h) in faces:
    cv2.rectangle(img, (x,y), (x+w, y+h), (0,225, 0), 2)

cv2.imshow("Image", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

26


# Eye Detection

In [1]:
import numpy as np
import cv2

img = cv2.imread("faces.jpeg", 1)
img = cv2.resize(img, (0,0), fx=.2, fy=.2)
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
path = "haarcascade_eye.xml"

eye_cascade = cv2.CascadeClassifier(path)

eyes = eye_cascade.detectMultiScale(gray, scaleFactor=1.004, minNeighbors=20, minSize=(10,10))
print(len(eyes))

for (x, y, w, h) in eyes:
    xc = (x + x+w)/2
    yc = (y + y+h)/2
    radius = w/2
    cv2.circle(img, (int(xc), int(yc)), int(radius), (255,0,0), 2)

cv2.imshow("Image", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

40
